name: stretching
description: Stretching remake from scratch.
version: 2.0.1+21

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.15.0-42.0.dev <3.0.0'
  flutter: '>=2.6.0-0.0.pre'

dependencies:
  animations: ^2.0.1
  appsflyer_sdk: ^6.3.5+3
  async: ^2.8.2
  auto_size_text: ^3.0.0-nullsafety.0
  badges: ^2.0.1
  cached_network_image: ^3.1.0
  cached_video_player: ^2.0.0-dev.1
  carousel_slider: ^4.0.0
  catcher: ^0.6.8
  crypto: ^3.0.1
  darq: ^1.1.1
  device_calendar: ^4.0.1-dev.13167
  dio: ^4.0.0
  # draggable_scrollbar: ^0.1.0
  dropdown_below: ^1.0.0
  easy_localization: ^3.0.0
  expandable_text: ^2.2.0
  firebase_analytics: ^8.3.2
  firebase_core: ^1.6.0
  firebase_crashlytics: ^2.2.1
  firebase_messaging: ^10.0.7
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_keyboard_visibility: ^5.0.3
  flutter_native_timezone: ^2.0.0
  flutter_riverpod: ^1.0.0-dev.7
  flutter_stories: ^0.3.0
  geolocator: ^7.6.2
  google_maps_flutter: ^2.0.10
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.0-dev.7
  intl: ^0.17.0
  logger: ^1.1.0
  logging: ^1.0.2
  mask_text_input_formatter: ^2.0.0
  meta: ^1.7.0
  modal_bottom_sheet: ^2.0.0
  native_device_orientation: ^1.0.0
  package_info: ^2.0.2
  path: ^1.8.0
  path_provider: ^2.0.5
  permission_handler: ^8.1.6
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  random_string: ^2.3.1
  riverpod: ^1.0.0-dev.7
  smooth_page_indicator: ^1.0.0+2
  tcard: ^1.3.5
  timezone: ^0.8.0
  tinkoff_acquiring: ^3.0.4
  translit: ^2.0.0
  uni_links: ^0.5.1
  url_launcher: ^6.0.10
  validators: ^3.0.0
  webview_flutter: ^2.0.13

dependency_overrides:
  flutter_native_timezone: ^2.0.0
  timezone: ^0.8.0

dev_dependencies:
  args: ^2.3.0
  build_runner: ^2.1.2
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.2.3
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/google_map_style.json
    - assets/logo.gif
    - assets/emoji/10084.png
    - assets/emoji/1f499.png
    - assets/emoji/1f517.png
    - assets/emoji/1f525.png
    - assets/emoji/1f609.png
    - assets/emoji/1f60d.png
    - assets/emoji/1f610.png
    - assets/emoji/1f61e.png
    - assets/emoji/1f622.png
    - assets/emoji/1f623.png
    - assets/emoji/1f62c.png
    - assets/emoji/1f631.png
    - assets/emoji/1f633.png
    - assets/emoji/1f642.png
    - assets/emoji/1f64c-1f3fb.png
    - assets/emoji/1f914.png
    - assets/emoji/1f918.png
    - assets/emoji/1f929.png
    - assets/emoji/1f964.png
    - assets/emoji/1f9d8.png
    - assets/emoji/23f1-fe0f.png
    - assets/emoji/26a1.png
    - assets/emoji/270c-fe0f.png
    - assets/emoji/2764-fe0f.png
    - assets/messengers/facebook.png
    - assets/messengers/telegram.png
    - assets/messengers/viber.png
    - assets/messengers/vk.png
    - assets/messengers/whatsApp.png
    - assets/translations/ru-RU.json

  fonts:
    - family: IconsCG
      fonts:
        - asset: assets/fonts/IconsCG.ttf

    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Thin.ttf
          weight: 100
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-UltraLight.ttf
          weight: 200
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Light.ttf
          weight: 300
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Medium.ttf
          weight: 500
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Semibold.ttf
          weight: 600
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Heavy.ttf
          weight: 800
        - asset: assets/fonts/SFUIDisplay/SFUIDisplay-Black.ttf
          weight: 900

flutter_icons:
  android: true
  ios: true
  image_path: icon.png
  remove_alpha_ios: true
  # image_path_ios: 'assets/icon/icon_ios.png'

flutter_native_splash:
  # color: '#ffffff'
  image: assets/splash/logo.png
  image_dark: assets/splash/logo.png
  background_image: assets/splash/background.png
  background_image_dark: assets/splash/background.png
  fullscreen: true
  # android_gravity: center
  # ios_content_mode: center
