name: stretching
description: Stretching remake from scratch.
version: 0.1.2

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: none # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.15.0-42.0.dev <3.0.0'
  flutter: '>=2.6.0-0.0.pre'

dependencies:
  animations: ^2.0.1
  auto_size_text: ^3.0.0-nullsafety.0
  cached_network_image: ^3.1.0
  connectivity: ^3.0.6
  custom_info_window: ^1.0.1
  darq: ^1.1.1
  dio: ^4.0.0
  draggable_scrollbar: ^0.1.0
  easy_localization: ^3.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.0-dev.6
  geolocator: ^7.4.1
  google_maps_flutter: ^2.0.6
  hawk_fab_menu:
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  hooks_riverpod: ^1.0.0-dev.6
  intl: ^0.17.0
  logger: ^1.0.0
  mask_text_input_formatter: ^2.0.0
  meta: ^1.7.0
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.1.4+2
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.3.0
  riverpod: ^1.0.0-dev.6

dev_dependencies:
  args: ^2.2.0
  build_runner: ^2.0.6
  flutter_launcher_icons: ^0.9.1
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

flutter:
  assets:
    - assets/google_map_style.json
    - assets/translations/ru-RU.json
    - assets/emoji/

  fonts:
    - family: IconsCG
      fonts:
        - asset: assets/fonts/IconsCG.ttf

flutter_icons:
  android: true
  ios: true
  image_path: icon.png
  remove_alpha_ios: true
  # image_path_ios: 'assets/icon/icon_ios.png'

flutter_native_splash:
  color: '#ffffff'
  image: icon.png
  color_dark: '#222222'
  image_dark: icon.png
  fullscreen: true
  # android_gravity: center
  # ios_content_mode: center
